name: Deploy to Render

on:
  push:
    branches:
      - main  # Altere para o nome da sua branch principal se for diferente de main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use a versão do Python que você está utilizando
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test compile
        run: python -m py_compile server.py
      - name: Deploy to Render
        uses: actions/curl@v2
        with:
          url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          method: POST
